// <auto-generated />
namespace ProjectoAlexa.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddConcursoProvaTempoExame : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConcursoProvaTempoExame));
        
        string IMigrationMetadata.Id
        {
            get { return "202103051528480_AddConcursoProvaTempoExame"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
